services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-agency-backend
    container_name: travel-agency-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:root@host.docker.internal/project-management-tool
    volumes:
      - .:/app
      - /app/node_modules
