name: Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables from .env
        run: |
          export $(cat .env | xargs)
        shell: bash

      - name: Set DATABASE_URL from GitHub Secrets
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV


      - name: Install dependencies
        run: |
          yarn install

      - name: Generate prisma client
        run: npx prisma generate

      - name: Migrate prisma schema
        run: |
          npx prisma migrate deploy

      - name: Build application
        run: |
          yarn run build

      - name: Deploy to VPS
        run: |
          pm2 stop all || true
          pm2 start dist/main.js --name "nestjs-app"
